# Generated by Django 6.0 on 2026-01-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.TextField(choices=[('Contacts', 'Contacts'), ('GroupChat', 'GroupChat')], default='Contacts', max_length=20),
        ),
    ]
