# Generated by Django 6.0 on 2026-01-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_interests'),
        ('users', '0009_userprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(related_name='user_profiles', to='core.interest'),
        ),
    ]
