# Generated by Django 6.0 on 2025-12-23 09:25

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        UnaccentExtension(),
    ]
