# Generated by Django 6.0 on 2026-01-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_user_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interests',
            field=models.ManyToManyField(related_name='posts', to='core.interest'),
        ),
    ]
